# osl-dynamics version: 2.3.1
batch_size: 64
baum_welch_implementation: log
best_of: 1
covariances_epsilon: 1.0e-06
covariances_regularizer: null
diagonal_covariances: false
gradient_clip: null
init_method: random_state_time_course
init_take: 1.0
initial_covariances: null
initial_means: null
initial_state_probs: null
initial_trans_prob: null
learn_covariances: true
learn_initial_state_probs: true
learn_means: false
learn_trans_prob: true
learning_rate: 0.01
loss_calc: mean
lr_decay: 0.1
means_regularizer: null
model_name: HMM
multi_gpu: false
multiple_dynamics: false
n_channels: 64
n_epochs: 20
n_init: 3
n_init_epochs: 1
n_modes: null
n_states: 6
optimizer: adam
sequence_length: 200
strategy: null
trans_prob_prior: null
trans_prob_update_delay: 5
trans_prob_update_forget: 0.7
